services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-visibilitylog
    